@FabuRobotics.Shop.Api_HostAddress = http://localhost:5502

POST {{FabuRobotics.Shop.Api_HostAddress}}/api/shop
Accept: application/json
Content-Type: application/json
{
  "customerId": "2",
  "sku": "fb-02",
  "quantity": 1
}
###
